services:
  app_blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_blue
    restart: always

  app_green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_green
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green